version: "3"
services:
  graph-node:
    container_name: indexer
    image: graphprotocol/graph-node:v0.38.0
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: "ipfs:5001"
      GRAPH_ETH_CALL_BY_NUMBER: 1
      GRAPH_NO_EIP_1898_SUPPORT: 1
      GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: 1
      GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: 1
      GRAPH_STORE_WRITE_BATCH_DURATION: 10
      GRAPH_STORE_WRITE_BATCH_SIZE: 8000
      ETHEREUM_REORG_THRESHOLD: 16
      ethereum: "bsc:https://bsc.drpc.org"
      RUST_LOG: info
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:v0.34.1
    ports:
      - "5001:5001"
    volumes:
      - ./graph_data/ipfs:/data/ipfs
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - ./graph_data/postgres:/var/lib/postgresql/data
